[package]
name = "benches"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]

[dev-dependencies]
criterion = { version = "0.6.0", default-features = false }

[[bench]]
name = "hex_conversion"
path = "hex_conversion.rs"
harness = false
