[package]
name = "benches"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]

[dev-dependencies]
criterion = "0.6.0"

[[bench]]
name = "hex_conversion"
path = "hex_conversion.rs"
harness = false
