[package]
name = "extra_tests"
version = "0.0.0"
edition = "2024"

[dependencies]
short_type_id = { path = "../short_type_id" }

[features]
unsafe_remove_duplicate_checks = ["short_type_id/unsafe_remove_duplicate_checks"]
